export const selectedIngredients = [
  {
    "_id": "60d3b41abdacab0026a733c6",
    "name": "Краторная булка N-200i",
    "type": "bun",
    "proteins": 80,
    "fat": 24,
    "carbohydrates": 53,
    "calories": 420,
    "price": 1255,
    "image": "https://code.s3.yandex.net/react/code/bun-02.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
    "__v": 0
  },
  {
    "_id": "60d3b41abdacab0026a733ca",
    "name": "Говяжий метеорит (отбивная)",
    "type": "main",
    "proteins": 800,
    "fat": 800,
    "carbohydrates": 300,
    "calories": 2674,
    "price": 3000,
    "image": "https://code.s3.yandex.net/react/code/meat-04.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/meat-04-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/meat-04-large.png",
    "__v": 0
  },
  {
    "_id": "60d3b41abdacab0026a733cc",
    "name": "Соус Spicy-X",
    "type": "sauce",
    "proteins": 30,
    "fat": 20,
    "carbohydrates": 40,
    "calories": 30,
    "price": 90,
    "image": "https://code.s3.yandex.net/react/code/sauce-02.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/sauce-02-large.png",
    "__v": 0
  },
  {
    "_id": "60d3b41abdacab0026a733cc",
    "name": "Соус Spicy-X",
    "type": "sauce",
    "proteins": 30,
    "fat": 20,
    "carbohydrates": 40,
    "calories": 30,
    "price": 90,
    "image": "https://code.s3.yandex.net/react/code/sauce-02.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/sauce-02-large.png",
    "__v": 0
  },
  {
    "_id": "60d3b41abdacab0026a733ce",
    "name": "Соус традиционный галактический",
    "type": "sauce",
    "proteins": 42,
    "fat": 24,
    "carbohydrates": 42,
    "calories": 99,
    "price": 15,
    "image": "https://code.s3.yandex.net/react/code/sauce-03.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/sauce-03-large.png",
    "__v": 0
  },
  {
    "_id": "60d3b41abdacab0026a733d1",
    "name": "Плоды Фалленианского дерева",
    "type": "main",
    "proteins": 20,
    "fat": 5,
    "carbohydrates": 55,
    "calories": 77,
    "price": 874,
    "image": "https://code.s3.yandex.net/react/code/sp_1.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/sp_1-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/sp_1-large.png",
    "__v": 0
  },
  {
    "_id": "60d3b41abdacab0026a733d1",
    "name": "Плоды Фалленианского дерева",
    "type": "main",
    "proteins": 20,
    "fat": 5,
    "carbohydrates": 55,
    "calories": 77,
    "price": 874,
    "image": "https://code.s3.yandex.net/react/code/sp_1.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/sp_1-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/sp_1-large.png",
    "__v": 0
  },
  {
    "_id": "60d3b41abdacab0026a733d2",
    "name": "Кристаллы марсианских альфа-сахаридов",
    "type": "main",
    "proteins": 234,
    "fat": 432,
    "carbohydrates": 111,
    "calories": 189,
    "price": 762,
    "image": "https://code.s3.yandex.net/react/code/core.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/core-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/core-large.png",
    "__v": 0
  },
  {
    "_id": "60d3b41abdacab0026a733d2",
    "name": "Кристаллы марсианских альфа-сахаридов",
    "type": "main",
    "proteins": 234,
    "fat": 432,
    "carbohydrates": 111,
    "calories": 189,
    "price": 762,
    "image": "https://code.s3.yandex.net/react/code/core.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/core-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/core-large.png",
    "__v": 0
  },
  {
    "_id": "60d3b41abdacab0026a733d2",
    "name": "Кристаллы марсианских альфа-сахаридов",
    "type": "main",
    "proteins": 234,
    "fat": 432,
    "carbohydrates": 111,
    "calories": 189,
    "price": 762,
    "image": "https://code.s3.yandex.net/react/code/core.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/core-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/core-large.png",
    "__v": 0
  }
];

export const fakeOrderNumber = '034536'; 